rds:
  identifier: adventure-works-joomla-db
  engine: MySQL
  version: 8.0.35
  instance_class: db.t3.micro
  
  storage:
    type: gp3
    size: 20
    encrypted: true
    
  network:
    subnet_group: adventure-works-db-subnet-group
    security_group: adventure-works-db-sg
    security_group_id: adventure-works-db-sg (sg-08db77ff5a3df5b7b)
    vpc_id: adventure-works-vpc (vpc-02adea5348b909d4f)
    publicly_accessible: false
    availability_zone: us-east-1a
    
  endpoint:
    address: adventure-works-joomla-db.c85y0o6sii45.us-east-1.rds.amazonaws.com
    port: 3306
    
  database:
    name: joomladb
    master_username: admin

    
  backup:
    retention_period: 7
    backup_window: 03:00-04:00
    maintenance_window: Mon:04:00-Mon:05:00
    
  monitoring:
    enabled: true
    interval: 60

joomla_user:
  username: joomlauser

  privileges: ALL PRIVILEGES on joomladb.*
  host: '%'